{% set name = "azure-mgmt-monitor" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 04bd89d74fe47f966b09e3256ffefcfa5c1a51057a6b33c092afe5ae17a1a7b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.monitor

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Microsoft Azure Monitor Client Library for Python.


extra:
  recipe-maintainers:
    - tim-werner
