schema_version: 1

context:
  name: azure-mgmt-monitor
  version: 7.0.0b1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 591e1864cc389e3925a40464ba3b119ddea7c1367c339bd715ccbd01f2fda23e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.monitor
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Microsoft Azure Monitor Client Library for Python.
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
