schema_version: 1

context:
  name: azure-mgmt-monitor
  version: 0.11.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: c6e1fe83dd2ddffa7f6d90c7aa63b3128042396a3893c14dc4816ad28cb15016

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.monitor
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Microsoft Azure Monitor Client Library for Python.
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
